version: '3.9'
services:
  nats:
    image: nats
    ports:
      - '4222:4222' # Porta para clientes
      - '8222:8222' # Porta HTTP para relatórios de informações
      - '6222:6222' # Porta de roteamento para clustering
    networks:
      - nats
    command: ['--http_port', '8222']
    environment:
      - NATS_CLUSTER_NAME=NATS
      - NATS_CLUSTER=nats://0.0.0.0:6222

networks:
  nats:
    driver: bridge
