apiVersion: v1
kind: Service
metadata:
  name: svc-ts-ms-paymentmanager
  labels:
    app: svc-ts-ms-paymentmanager
spec:
  selector:
    app: ts-ms-paymentmanager-deployment
  type: LoadBalancer
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
